### ISSUE TITLE
Rename join to implode?

### ISSUE THREAD

**Issue by Moskito89** [roberto-butti/some-drops-of-php#22]
In [02-array/02-arr-join](https://github.com/roberto-butti/some-drops-of-php/blob/main/src/content/docs/02-array/02-arr-join.md), the function `join` is being used which is an alias for `implode` ([https://www.php.net/join](https://www.php.net/join)). I think it would make sense to use the original function — or do I miss something?

**Comment by roberto-butti** [comment]
Thank you @Moskito89 ,  Yes i agree. Thank you for raising this.
So the tasks are:
- renaming the file from 02-arr-join to 02-arr-implode
- changing the references in the file from join() to implode()
- adding a note at the end of the markdown file mentioning that you can eventually use join , because it is an alias of implode
- check and fix the examples

I set the hacktoberfest label in case someone wants to take care of this issue.

**Comment by ngdangtu-vn** [comment]
I prefer the term `join` as it is easily to search rather than `implode`. Whenever I google the way to concatate all str elements in an array, I always use `join` keyword because:

a. It's short, easy to type, hard to make typo. Did you notice my typo of **concatenate**? I make that mitake all the time.
b. It is least academic meaning, pretty common name helps everyone remember easily
c. From a and b, I can say it will boost more SEO for the book. Which will help more developers who look for studying resource.

So I'm strongly disagree. @roberto-butti, please think twice on this case, and more similar cases. Which do you prefer? academic style for minority group or common style for vast variety people. Your choice.

**Comment by roberto-butti** [comment]
good point @ngdangtu-vn  , thank you for raise all of these points.
considering the feedback of @Moskito89  and your feedback i would like to proceed in this way:
- keep the current file name
- in the explanation and the title focusing on the "goal" , the "purpose" of the implode and join function. In the explanation referring to the implode function
- add a callout note where i can explain the join function (that it is an alias etc)
- in the example shows both functions

**Comment by roberto-butti** [comment]
Hi @Moskito89 and @ngdangtu-vn for all the valuable feedback, i merged a PR for using implode and mentioning that the join is an alias for implode.
Thank you!
